"""add_reset

Revision ID: eca7eb441fbb
Revises: 8bfac8952c78
Create Date: 2023-04-23 22:32:49.427416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca7eb441fbb'
down_revision = '8bfac8952c78'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_tocken')
    # ### end Alembic commands ###
